include::./Header.adoc[]

= Tutorial
Delivery v{deliveryVersion}, {generationDate}

== Configuration

To use delivery, you just have to apply the plugin in your project.

```Groovy
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.leroymerlin.plugins:delivery-plugin:LAST_VERSION'
	}
}

apply plugin: 'com.leroymerlin.delivery'
```
Create a *version.properties* file in your module. This file will contain your module *version*, *versionId* and *projectName* the plugin needs.

NOTE: You can override the version.properties file path with *versionFilePath* property. This property has to be in *gradle.properties* or eventually in *delivery.properties*. You could also override other properties name with *versionKey*, *versionIdKey* and *projectNameKey*.

Configure the delivery gradle extension in your build.gradle to fit your need.

```Groovy
delivery {
    // RepositoryHandler to archive your build artifact
    archiveRepositories = project.ext.archiveRepositories //default value

    // project flow container
    flows {
        ...
    }
    // artifact signing properties container
    signingProperties {
        ...
    }
}
```

NOTE: You can find more documentation about archiveRepositories on the https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html[official groovy website]. +
Flows and signingProperties DSL are based on http://mrhaki.blogspot.fr/2016/02/gradle-goodness-create-objects-with-dsl.html[Gradle NamedDomainObjectContainer].

You can use system properties to inject scm credentials and set your project version.

* *SCM_EMAIL* // git email
* *SCM_USER* // git username
* *SCM_PASSWORD* // git password
* *VERSION* // override actual version

== Flows

Flow allows you to configure release steps. +
Once a flow is configured, you can run it by calling the gradle task named "yourFlowName+*Flow*".

.Methods provided by Delivery:
[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=flowExample]
----

NOTE: To simplify your life, Delivery provides an implementation of git release flow. +
You just have to call *releaseGitFlow* to use it.

[source,groovy]
----
include::{groovyDir}com/leroymerlin/plugins/DeliveryPlugin.groovy[tags=gitReleaseFlow]
----

== Signing config

SigningConfiguration allows you to configure artifacts signatures. +
A configuration is a set of key/value pair.
You can externalize critical data using a https://en.wikipedia.org/wiki/.properties[properties file]

.Example:
[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingFileExample]
----

IMPORTANT: You should consider not to put keystore and credentials inside your repository.

=== Android

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingAndroidExample]
----

=== iOS

NOTE: iOS support is based on the open source project https://github.com/openbakery/gradle-xcodePlugin[gradle-xcodePlugin]

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingiOSExample]
----

=== Ionic

NOTE: Ionic support is only available with the last Ionic version

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingIonicExample]
----

=== React Native

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingReactExample]
----

== Custom projects

If your project doesn't answer the Delivery's supported configurations (iOS, Android, Ionic, Java, Groovy), you can define your own configurator.

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=configuratorExample]
----

To achieve your project's build, you have to create one or more DeliveryBuild tasks, and define the variant names and output files.

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=deliveryBuildExample]
----