include::./Header.adoc[]

= Tutorial
Delivery v{deliveryVersion}, {generationDate}


== Configuration

To use delivery, you just have to apply the plugin in your project.


```Groovy
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.leroymerlin.plugins:delivery-plugin:LAST_VERSION'
	}
}

apply plugin: 'com.leroymerlin.delivery'
```
Create *version.properties* in your module. This file will contain your module *version*, *versionId* and *projectName* the plugin needs.

NOTE: You can override the version.properties file path with *versionFilePath* property. This property has to be in *gradle.properties* or eventually in *delivery.properties*. You could also override other properties name with *versionKey*, *versionIdKey* and *projectNameKey*.

Configure the delivery gradle extension in your build.gradle to fit your need

```Groovy
delivery {
    // RepositoryHandler to archive your build artifact
    archiveRepositories = project.ext.archiveRepositories //default value

    // project flow container
    flows {
        ...
    }
    // artifact signing properties container
    signingProperties {
        ...
    }
}
```

NOTE: You can find more documentation about RepositoryHandler on the https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html[official groovy website]

You can use system properties to inject scm credentials and to set your project version.

* *SCM_EMAIL* // git email
* *SCM_USER* // git username
* *VERSION* // actual version

=== Flows

Flow allows you to configure release steps that fit your project. +
Once a flow is configured you can run it by calling the gradle task named "yourFlowName+*Flow*".

.Methods provide by Delivery:
[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=flowExample]
----

NOTE: To simplify your life Delivery suggest an implementation of git release flow. +
You just have to call *releaseGitFlow* to use it.

[source,groovy]
----
include::{groovyDir}com/leroymerlin/plugins/DeliveryPlugin.groovy[tags=gitReleaseFlow]
----

=== Signing config

You can sign your mobile projects with a signing configuration. +
You have to set a key/value pair inside a https://en.wikipedia.org/wiki/.properties[properties file]

IMPORTANT: Don't forget to put it outside of your git repository.

==== Android

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingAndroidExample]
----

.Android
[cols="^,^",options="header"]
|==========================
|Key  |Value
|storePassword  |Your keystore file password
|keyPassword |Your keystore password
|keyAlias  |Your keystore alias
|storeFile  |Your keystore file
|==========================

==== iOS

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingiOSExample]
----

.iOS
[cols="^,^",options="header"]
|==========================
|Key  |Value
|certificateURI  |Your certificate
|certificatePassword |Your certificate's password
|mobileProvisionURI  |Your developer provisioning profile
|==========================

==== Ionic

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingIonicExample]
----