include::./Header.adoc[]

= Tutorial
Delivery v{deliveryVersion}, {generationDate}

== Configuration

To use delivery, you just have to apply the plugin in your project.

```Groovy
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.leroymerlin.plugins:delivery-plugin:LAST_VERSION'
	}
}

apply plugin: 'com.leroymerlin.delivery'
```
Create a *version.properties* file in your module. This file will contain your module *version*, *versionId* and *artifact* the plugin needs.

Configure the delivery gradle extension in your build.gradle to fit your need.

```Groovy
delivery {
    // Enable the default git flow
    enableReleaseGitFlow = false

    // Link submodules's Install and Upload tasks with parent's tasks
    autoLinkSubModules = false

    // Define submodules path to link Install and Upload tasks with the project build tasks
    linkedSubModules = []

    // RepositoryHandler to archive your build artifact
    archiveRepositories = project.ext.archiveRepositories //default value

    // project flow container
    flows {
        ...
    }
    // artifact signing properties container
    signingProperties {
        ...
    }
}
```

NOTE: You can find more documentation about archiveRepositories on the https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.RepositoryHandler.html[official groovy website]. +
Flows and signingProperties DSL are based on http://mrhaki.blogspot.fr/2016/02/gradle-goodness-create-objects-with-dsl.html[Gradle NamedDomainObjectContainer].

You can use system properties to inject scm credentials, set your project version and define your project group.

* *SCM_EMAIL* // git email
* *SCM_USER* // git username
* *SCM_PASSWORD* // git password
* *VERSION* // override actual version
* *GROUP_ID* // override project's group

== Flows

Flow allows you to configure release steps. +
Once a flow is configured, you can run it by calling the gradle task named "yourFlowName+*Flow*".

.Methods provided by Delivery:
[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=flowExample]
----

NOTE: To simplify your life, Delivery provides an implementation of git release flow.

link:Flows.html[See preconfigured Flows]

== Version.properties

Delivery use version.properties file define in project's root path

[source,groovy]
----
include::{testProjectDir}multiModules/version.properties[]
----

== Signing config

SigningConfiguration allows you to configure artifacts signatures. +
A configuration is a set of key/value pair.
You can externalize critical data using a https://en.wikipedia.org/wiki/.properties[properties file]

.Example:
[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingFileExample]
----

WARNING: You should consider not to put keystore and credentials inside your repository.

=== Android

NOTE: Delivery now support Android projects using Android plugin 2.x.x and 3.x.x

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingAndroidExample]
----

=== iOS

NOTE: iOS support is based on the open source project https://github.com/openbakery/gradle-xcodePlugin[gradle-xcodePlugin]

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingiOSExample]
----

=== Ionic

IMPORTANT: Ionic support is only available with the last Ionic version

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingIonicExample]
----

=== React Native

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=signingReactExample]
----

== Multi Modules

You can link *Install* task and *Upload* task from childs modules with parent module by using *autoLinkSubModules = true* or *linkedSubModules = 'subModule1', ...*

[source,groovy]
----
include::{testProjectDir}multiModules/build.gradle[tags=multiModulesExample]
----

NOTE: Look at the https://github.com/MobileTribe/delivery-gradle-plugin/tree/master/delivery-plugin/src/test/resources/multiModules[sample] for more informations

CAUTION: You need to apply Delivery on all modules you want to use with Delivery

== Custom projects

If your project doesn't answer the Delivery's supported configurations (iOS, Android, Ionic, Java, Groovy), you can define your own configurator.

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=configuratorExample]
----

To achieve your project's build, you have to create one or more DeliveryBuild tasks, and define the variant names and output files.

[source,groovy]
----
include::{testGroovyDir}com/leroymerlin/plugins/test/DeliveryPluginTest.groovy[tags=deliveryBuildExample]
----

== Logs

By default Delivery provide beautiful and colorful logs.
But if you prefer to watch classic logs you can set a system property or environment variable named *ugly*.

.Sample to disable color logs
TIP: gradle myFlow -Dugly

== Troubleshooting

=== Unknown error -1=ffffffffffffffff

If you're using Delivery with automation server like Jenkins for iOS builds, you may see this error happens. To solve this, we made the plugin to be able to unlock the Apple Keychain which can solve this problem. +

To use this feature, define a system property or environment variable named *KEYCHAIN_PASSWORD*.

.Command executed to unlock the Apple Keychain
TIP: security unlock-keychain -p $KEYCHAIN_PASSWORD ~/Library/Keychains/login.keychain-db