include::./Header.adoc[]

= Tutorial
Delivery v{deliveryVersion}, {generationDate}


== Configuration

To use delivery, you just have to apply the plugin in your project.


```Groovy
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
		classpath 'com.leroymerlin.plugins:delivery-plugin:LAST_VERSION'
	}
}

apply plugin: 'com.leroymerlin.delivery'
```
Create *version.properties* in your module. This file will contain your module *version*, *versionId* and *projectName* the plugin needs.

NOTE: You can override the version.properties file path with *versionFilePath* property. This property has to be in *gradle.properties* or eventually in *delivery.properties*. You could also override other properties name with *versionKey*, *versionIdKey* and *projectNameKey*.

Configure the delivery gradle extension in your build.gradle to fit your need

```Groovy
delivery {
    archiveRepositories {
        //fill with what you need
    }
    flows {
        //fill with what you need
    }
    signingProperties {
        //fill with what you need
    }
}
```
For Android and iOS applications, don’t forget to configure your own *signing.properties* file outside of your git repository. +
Android:
----
storePassword=myStorePassword
keyPassword=myKeyPassword
keyAlias=myKeyAlias
storeFile=myStoreFileLocation
----
iOS:

----
certificateURI=myCertificate
certificatePassword=myPassword
mobileProvisionURI=myMobileProvision
----

IMPORTANT: You can set the properties inside *build.gradle*, without using a *signing.properties*.

== Flows

Delivery provide default methods.

```Groovy
delivery {
    archiveRepositories {
        //fill with what you need
    }
    flows {
        //fill with what you need
    }
    signingProperties {
        //fill with what you need
    }
}
```